import type { Metadata } from "next";
import { geistMono, geistSans } from "@/app/ui/fontui";
import "./globals.css";
import StoreProvider from "./store/StoreProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <StoreProvider>
        <div className="flex-grow">{children}</div>
        </StoreProvider>
      </body>
    </html>
  );
}
